@startuml
'https://plantuml.com/class-diagram

interface Command {
+ execute()
}

class ConcreteCommand implements Command {
+ execute()
}
note right of ConcreteCommand
execute() {
receiver.action()
}
end note

class Receiver
class Client
class Invoker

Client -> Receiver
Client ..> ConcreteCommand
ConcreteCommand --> Receiver
Invoker o-> Command

@enduml