@startuml

title __FRAMEWORK's Class Diagram__\n

  namespace com.yuuy.spring.framework {
    interface com.yuuy.spring.framework.Autowired {
    }
  }
  

  namespace com.yuuy.spring.framework {
    class com.yuuy.spring.framework.BeanDefinition {
        - clazz : Class
        - scope : String
        + BeanDefinition()
        + getClazz()
        + getScope()
        + setClazz()
        + setScope()
    }
  }
  

  namespace com.yuuy.spring.framework {
    interface com.yuuy.spring.framework.BeanNameAware {
        {abstract} + setBeanName()
    }
  }
  

  namespace com.yuuy.spring.framework {
    interface com.yuuy.spring.framework.BeanPostProcessor {
        {abstract} + postProcessorAfterInitialization()
        {abstract} + postProcessorBeforeInitialization()
    }
  }
  

  namespace com.yuuy.spring.framework {
    interface com.yuuy.spring.framework.Component {
        {abstract} + value()
    }
  }
  

  namespace com.yuuy.spring.framework {
    interface com.yuuy.spring.framework.ComponentScan {
        {abstract} + value()
    }
  }
  

  namespace com.yuuy.spring.framework {
    interface com.yuuy.spring.framework.InitializeBean {
        {abstract} + afterPropertiesSet()
    }
  }
  

  namespace com.yuuy.spring.framework {
    class com.yuuy.spring.framework.MyApplicationContext {
        - beanDefinitionMap : Map<String, BeanDefinition>
        - beanPostProcessors : List<String>
        - configClass : Class
        - singletonPools : Map<String, Object>
        + MyApplicationContext()
        + getBean()
        - createBean()
        - createSingleton()
        {static} - getClass()
        - getScanPath()
        - register()
        - registerBeanDefinition()
        - registerBeanPostProcessor()
        - scan()
    }
  }
  

  namespace com.yuuy.spring.framework {
    interface com.yuuy.spring.framework.Scope {
        {abstract} + value()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
