@startuml
'https://plantuml.com/activity-diagram-beta

start
:create application context;
:get scan path;
:get beans annotated with @Component;
:construct a bean definition map based on scope, class;
if (scope is singleton) then (yes)
    :create singleton bean and add it to the pool;
endif
stop
start
:get bean;
if (scope is singleton) then (yes)
    :return the bean from the pool;
else
    :create the prototype bean;
    :return the bean;
endif
stop

@enduml
