@startuml
'https://plantuml.com/class-diagram

class Client
abstract class Prototype {
+ clone()
}
class ConcretePrototype1 extends Prototype {
+ clone()
}
class ConcretePrototype2 extends Prototype {
+ clone()
}

Prototype <- Client

@enduml