@startuml

abstract class Builder {
+ buildPart()
}

class ConcreteBuilder extends Builder {
+ buildPart()
}

class Client

class Director {
+ construct()
}

class Product

Director o-> Builder
Director <- Client
ConcreteBuilder <-- Client
Product <- ConcreteBuilder


@enduml