@startuml
'https://plantuml.com/class-diagram

interface ProductA
class ConcreteProductA implements ProductA
interface ProductB
class ConcreteProductB implements ProductB

abstract class AbstractFactory {
# createProductA() : ProductA
# createProductB() : ProductB
}

class ConcreteFactory extends AbstractFactory {
# createProductA() : ConcreteProductA
# createProductB() : ConcreteProductB
}

ConcreteProductA <.... ConcreteFactory : return a concrete A
ConcreteProductB <.... ConcreteFactory : return a concrete B

@enduml