@startuml
'https://plantuml.com/class-diagram

class Client
abstract class Handler {
# successor : Handler
+ handleRequest(request)
}

class ConcreteHandler1 implements Handler {
# successor : Handler
+ handleRequest(request)
}
class ConcreteHandler2 implements Handler {
# successor : Handler
+ handleRequest(request)
}

Client -> Handler : send request
Handler <- Handler : successor


@enduml